services:
  waha:
    image: devlikeapro/waha
    container_name: waha
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - WAHA_API_KEY=${WAHA_API_KEY}
      - WHATSAPP_DEFAULT_ENGINE=NOWEB
    volumes:
      - waha_sessions:/app/.sessions

volumes:
  waha_sessions: